# Generated by Django 4.2.11 on 2024-05-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peachyapp', '0002_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
